GOOGLE_API_KEY = "AIzaSyDzcZU5hQ4nbUV5sYr5tpESCP_2214wfJQ"
GOOGLE_CSE_ID = "26b2674b26b9d4a6b"
[looker]
client_id = "9SmvfT236sFgqs2NZrsw"
client_secret = "y9qzXvWWt3zybG2ccg2mCtQb"
base_url = "https://igmprinting.cloud.looker.com/"